### ISSUE TITLE
Internal Server Error for subscriptions

### ISSUE THREAD

**Issue by marcopolomercader** [stephanediondev/elasticsearch-admin#71]
Hellooo, first of all what a nice tool! Really awesome and helpful, also not deprecated as many others... important! :joy:. I'm having some issues that I would love to solve for production.
I'm using last version available (9 Sept. 2023) from Docker, and using DockerHub for testing.

When trying to access the subscriptions tab:
```
Internal Server Error
The controller for URI "/admin/subscriptions" is not callable: Environment variable not found: "MAILER_DSN".

File: /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php
Line: 76
Route: app_subscriptions
Installation type: docker
PHP version: 8.2.10
Symfony version: 6.3.4
Elasticsearch version: 8.10.0
Browser: Chrome 116.0
OS: Windows 10
```

This is the same error but from the logs:
`{"message":"Uncaught PHP Exception InvalidArgumentException: \"The controller for URI \"/admin/subscriptions\" is not callable: Environment variable not found: \"MAILER_DSN\".\" at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 76","context":{"exception":{"class":"InvalidArgumentException","message":"The controller for URI \"/admin/subscriptions\" is not callable: Environment variable not found: \"MAILER_DSN\".","code":0,"file":"/var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php:76","previous":{"class":"Symfony\\Component\\DependencyInjection\\Exception\\EnvNotFoundException","message":"Environment variable not found: \"MAILER_DSN\".","code":0,"file":"/var/www/html/vendor/symfony/dependency-injection/EnvVarProcessor.php:193"}}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2023-09-20T12:54:57.472467+00:00","extra":{}}`

Also, when accessing to Notifications tab(/admin/app-notifications) doesn't show nothing. Maybe related to the previous error.
There's some other tabs that throw an Internal Server Error such as Snapshots tab (/admin/snapshots), but in this case, personally I don't really need it.

Is this errors from my testing environment or is an application related error? Thanks for help, appreciate it

**Comment by stephanediondev** [comment]
Hi

Sorry I don't have considered the subscriptions with Docker

First thing todo:

Add 2 environment variables. But you need a SMTP server with credentials (or there is a service like sendmail to add in the container)

```
MAILER_DSN=smtp://user:password@host:port/?encryption=ssl
SENDER_ADDRESS=example@example.com
```

Then you need the set the cron script: here I can improve and add the command automatically on container creation

```
crontab -e
# m h dom mon dow command
*/5 * * * * cd /var/www/html && bin/console app:send-notifications
```

In /admin/app-notifications you will have the history with all the notifications sent

<img width="1130" alt="image" src="https://github.com/stephanediondev/elasticsearch-admin/assets/528192/2420e724-b0a9-4f07-9b1a-b6f4ff42f703">

<img width="353" alt="image" src="https://github.com/stephanediondev/elasticsearch-admin/assets/528192/9f2ba9bf-689a-4a70-a8d8-550eb6c91921">

**Comment by stephanediondev** [comment]
After some tests, it's difficult for me to have cron running in container, I don't have enough experience with Docker

**Comment by fdefiru** [comment]
Thank you for the wuick response. It was nearly impossible for me to run the notifications without

**Comment by stephanediondev** [comment]
Hi

About the notifications, you need also to set the environment variables VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY.
There is a command to generate the values ```bin/console app:generate-vapid```
This is required for the Push API.


The errors related to snapshots and repositories are not due to your Docker installation.
This project is very confidential, not a lot of users. I tried to cover multiple ES versions, but still you can have surprises.

I think you have a repository with a number as name.
And when ES returns the JSON, the repository key is an integer instead of a string.
And some functions in the application were defined to have a string for the name.

See "123" as key for the repository name

<img width="602" alt="image" src="https://github.com/stephanediondev/elasticsearch-admin/assets/528192/864bfbfe-3acc-461c-8ce9-af8081f0ae08">


I made a new release to fix that (convert to string).


I think the only challenge with Docker is to have the nofications working.

**Comment by fdefiru** [comment]
Hey! Thank you very much for that release.

It was impossible for me to make the notifications working due to the crontab thing. Doesn't care because I already made the notifications through prometheus.

The application is awesome and really helpful. As a suggestions the app could have the ability to list multiple clusters  like [Cerebro](https://github.com/lmenezes/cerebro), by necessity, not all at the same time. All in all, it's an amazing application. Also, really fast answer. 😉
